title: Abdul Basit Ali | Software Engineer
description: Full-Stack Mobile & Web Solutions Developer
theme: jekyll-theme-primer
baseurl: "/bstali"
url: "https://bstali.github.io"

# Build settings
markdown: GFM
plugins:
  - jekyll-github-metadata
  - jekyll-seo-tag